#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
--------------------------------------------
    _          _   _ _      __  __    _____
   / \   _ __ | |_(_) | __ _\ \/ /   |___ /
  / _ \ | `_ \| __| | |/ _` |\  /_____ |_ \
 / ___ \| | | | |_| | | (_| |/  \_____|__) |
/_/   \_\_| |_|\__|_|_|\__,_/_/\_\   |____/

--------------------------------------------
GID/UID
--------------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
--------------------------------------------
"
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
